#!/usr/bin/env bash
# Reference deploy script generated by `vibew bundle` for myproject.
# Runs LOCALLY. Ships this bundle to user@host, loads the image, brings
# the stack up, and probes /_vibewarden/health. Edit freely — vibew
# will never modify this file.
set -euo pipefail

if [[ $# -ne 1 ]]; then
  echo "usage: $0 <user@host[:/remote/path]>" >&2
  exit 1
fi

TARGET="$1"
USER_HOST="${TARGET%%:*}"
REMOTE_PATH="${TARGET#*:}"
if [[ "$REMOTE_PATH" == "$TARGET" ]]; then REMOTE_PATH="~/vibewarden-bundle"; fi

scp -r . "$USER_HOST:$REMOTE_PATH/"
ssh "$USER_HOST" "cd $REMOTE_PATH && docker compose pull && docker compose up -d"
sleep 3
if ! ssh "$USER_HOST" "curl -fsSL -m 10 http://localhost:8443/_vibewarden/health" >/dev/null; then
  ssh "$USER_HOST" "cd $REMOTE_PATH && docker compose logs --tail 50" >&2
  echo "deploy.sh: healthcheck failed — dumped last 50 log lines above" >&2
  exit 1
fi
echo "deploy.sh: healthy ($USER_HOST:$REMOTE_PATH)"
