package scaffold_test

import (
	"context"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"strings"
	"testing"

	scaffoldapp "github.com/vibewarden/vibewarden/internal/app/scaffold"
	"github.com/vibewarden/vibewarden/internal/domain/scaffold"
)

// fakeRenderer is a test double for ports.TemplateRenderer.
// It records calls and returns canned output.
type fakeRenderer struct {
	// rendered records (templateName -> rendered content).
	rendered map[string]string
	// renderErr, when non-nil, is returned by Render.
	renderErr error
	// renderToFileErr, when non-nil, is returned by RenderToFile.
	renderToFileErr error
}

func newFakeRenderer() *fakeRenderer {
	return &fakeRenderer{rendered: make(map[string]string)}
}

func (f *fakeRenderer) Render(templateName string, data any) ([]byte, error) {
	if f.renderErr != nil {
		return nil, f.renderErr
	}
	content := fmt.Sprintf("rendered:%s", templateName)
	f.rendered[templateName] = content
	return []byte(content), nil
}

func (f *fakeRenderer) RenderToFile(templateName string, data any, path string, overwrite bool) error {
	if f.renderToFileErr != nil {
		return f.renderToFileErr
	}
	if !overwrite {
		if _, err := os.Stat(path); err == nil {
			return fmt.Errorf("file exists: %w", os.ErrExist)
		}
	}
	// Write something to the path so callers can verify.
	content := fmt.Sprintf("rendered:%s", templateName)
	if err := os.MkdirAll(dirOf(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(content), 0o644)
}

// fakeDetector is a test double for ports.ProjectDetector.
type fakeDetector struct {
	cfg *scaffold.ProjectConfig
	err error
}

func (f *fakeDetector) Detect(_ string) (*scaffold.ProjectConfig, error) {
	return f.cfg, f.err
}

func TestService_Init(t *testing.T) {
	baseProject := &scaffold.ProjectConfig{
		Type: scaffold.ProjectTypeNode,
	}

	tests := []struct {
		name        string
		opts        scaffoldapp.InitOptions
		project     *scaffold.ProjectConfig
		detectorErr error
		wantErr     bool
		wantErrIs   error
		checkFiles  []string // filenames that must exist in the temp dir
		absentFiles []string // filenames that must NOT exist in the temp dir
	}{
		{
			name: "happy path generates vibewarden.yaml only (no docker-compose)",
			opts: scaffoldapp.InitOptions{
				UpstreamPort: 3000,
				SkipWrapper:  true,
			},
			project:     baseProject,
			checkFiles:  []string{"vibewarden.yaml"},
			absentFiles: []string{"docker-compose.yml"},
		},
		{
			name: "docker-compose.yml is never generated by init",
			opts: scaffoldapp.InitOptions{
				UpstreamPort: 3000,
			},
			project:     baseProject,
			absentFiles: []string{"docker-compose.yml"},
		},
		{
			name: "uses detected port when upstream port is zero",
			opts: scaffoldapp.InitOptions{
				UpstreamPort: 0,
				SkipWrapper:  true,
			},
			project: &scaffold.ProjectConfig{
				Type:         scaffold.ProjectTypeNode,
				DetectedPort: 4200,
			},
			checkFiles: []string{"vibewarden.yaml"},
		},
		{
			name: "uses default port 3000 when nothing detected",
			opts: scaffoldapp.InitOptions{
				UpstreamPort: 0,
				SkipWrapper:  true,
			},
			project:    &scaffold.ProjectConfig{Type: scaffold.ProjectTypeUnknown},
			checkFiles: []string{"vibewarden.yaml"},
		},
		{
			name: "errors when vibewarden.yaml exists without force",
			opts: scaffoldapp.InitOptions{
				UpstreamPort: 3000,
				SkipWrapper:  true,
			},
			project: &scaffold.ProjectConfig{
				Type:                scaffold.ProjectTypeGo,
				HasVibeWardenConfig: true,
			},
			wantErr:   true,
			wantErrIs: os.ErrExist,
		},
		{
			name: "existing docker-compose.yml is not an error (init does not check it)",
			opts: scaffoldapp.InitOptions{
				UpstreamPort: 3000,
				SkipWrapper:  true,
			},
			project: &scaffold.ProjectConfig{
				Type:             scaffold.ProjectTypeGo,
				HasDockerCompose: true,
			},
			checkFiles: []string{"vibewarden.yaml"},
		},
		{
			name: "force flag allows overwriting existing vibewarden.yaml",
			opts: scaffoldapp.InitOptions{
				UpstreamPort: 3000,
				Force:        true,
				SkipWrapper:  true,
			},
			project: &scaffold.ProjectConfig{
				Type:                scaffold.ProjectTypeNode,
				HasVibeWardenConfig: true,
			},
			checkFiles: []string{"vibewarden.yaml"},
		},
		{
			name: "detector error is propagated",
			opts: scaffoldapp.InitOptions{
				UpstreamPort: 3000,
			},
			detectorErr: errors.New("disk error"),
			wantErr:     true,
		},
		{
			name: "all features enabled produces vibewarden.yaml (no docker-compose)",
			opts: scaffoldapp.InitOptions{
				UpstreamPort:     8080,
				AuthEnabled:      true,
				RateLimitEnabled: true,
				TLSEnabled:       true,
				TLSDomain:        "example.com",
				SkipWrapper:      true,
			},
			project:     baseProject,
			checkFiles:  []string{"vibewarden.yaml"},
			absentFiles: []string{"docker-compose.yml"},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			dir := t.TempDir()

			project := tt.project
			if project == nil {
				project = baseProject
			}
			detector := &fakeDetector{cfg: project, err: tt.detectorErr}
			renderer := newFakeRenderer()

			svc := scaffoldapp.NewService(renderer, detector)
			err := svc.Init(context.Background(), dir, tt.opts)

			if (err != nil) != tt.wantErr {
				t.Fatalf("Init() error = %v, wantErr %v", err, tt.wantErr)
			}
			if tt.wantErrIs != nil && !errors.Is(err, tt.wantErrIs) {
				t.Errorf("Init() error = %v, want errors.Is(%v)", err, tt.wantErrIs)
			}

			for _, filename := range tt.checkFiles {
				path := dir + "/" + filename
				if _, err := os.Stat(path); err != nil {
					t.Errorf("expected file %q to exist: %v", path, err)
				}
			}

			for _, filename := range tt.absentFiles {
				path := dir + "/" + filename
				if _, err := os.Stat(path); err == nil {
					t.Errorf("file %q should not exist but does", path)
				}
			}
		})
	}
}

// dirOf returns the parent directory of a path, mimicking filepath.Dir but
// without importing path/filepath to keep the test self-contained.
func dirOf(path string) string {
	idx := strings.LastIndexByte(path, '/')
	if idx < 0 {
		return "."
	}
	return path[:idx]
}

// TestService_Init_EnsuresGitIgnore verifies that Init creates or updates
// .gitignore to include the .vibewarden/ entry.
func TestService_Init_EnsuresGitIgnore(t *testing.T) {
	baseProject := &scaffold.ProjectConfig{Type: scaffold.ProjectTypeNode}

	t.Run("creates .gitignore when absent", func(t *testing.T) {
		dir := t.TempDir()
		svc := scaffoldapp.NewService(newFakeRenderer(), &fakeDetector{cfg: baseProject})

		if err := svc.Init(context.Background(), dir, scaffoldapp.InitOptions{UpstreamPort: 3000, SkipWrapper: true}); err != nil {
			t.Fatalf("Init() unexpected error: %v", err)
		}

		gitignorePath := dir + "/.gitignore"
		if _, err := os.Stat(gitignorePath); err != nil {
			t.Fatalf(".gitignore not created: %v", err)
		}
	})

	t.Run("appends entry to existing .gitignore that lacks it", func(t *testing.T) {
		dir := t.TempDir()
		gitignorePath := dir + "/.gitignore"
		existing := "node_modules/\n.env\n"
		if err := os.WriteFile(gitignorePath, []byte(existing), 0o644); err != nil {
			t.Fatalf("writing .gitignore: %v", err)
		}

		svc := scaffoldapp.NewService(newFakeRenderer(), &fakeDetector{cfg: baseProject})
		if err := svc.Init(context.Background(), dir, scaffoldapp.InitOptions{UpstreamPort: 3000, SkipWrapper: true}); err != nil {
			t.Fatalf("Init() unexpected error: %v", err)
		}

		data, err := os.ReadFile(gitignorePath)
		if err != nil {
			t.Fatalf("reading .gitignore: %v", err)
		}
		if !strings.Contains(string(data), ".vibewarden/") {
			t.Errorf(".gitignore missing .vibewarden/ entry:\n%s", string(data))
		}
		if !strings.Contains(string(data), "node_modules/") {
			t.Errorf(".gitignore lost existing content:\n%s", string(data))
		}
	})

	t.Run("does not modify .gitignore that already has entry", func(t *testing.T) {
		dir := t.TempDir()
		gitignorePath := dir + "/.gitignore"
		existing := ".vibewarden/\nnode_modules/\n"
		if err := os.WriteFile(gitignorePath, []byte(existing), 0o644); err != nil {
			t.Fatalf("writing .gitignore: %v", err)
		}

		svc := scaffoldapp.NewService(newFakeRenderer(), &fakeDetector{cfg: baseProject})
		if err := svc.Init(context.Background(), dir, scaffoldapp.InitOptions{UpstreamPort: 3000, SkipWrapper: true}); err != nil {
			t.Fatalf("Init() unexpected error: %v", err)
		}

		data, err := os.ReadFile(gitignorePath)
		if err != nil {
			t.Fatalf("reading .gitignore: %v", err)
		}
		// Content should be unchanged (no duplicate entry).
		if string(data) != existing {
			t.Errorf(".gitignore was modified unnecessarily:\ngot:  %q\nwant: %q", string(data), existing)
		}
	})
}

// Verify fakeDetector satisfies the interface at compile time.
var _ interface {
	Detect(string) (*scaffold.ProjectConfig, error)
} = (*fakeDetector)(nil)

// Verify fakeRenderer satisfies the ports.TemplateRenderer interface.
var _ interface {
	Render(string, any) ([]byte, error)
	RenderToFile(string, any, string, bool) error
} = (*fakeRenderer)(nil)

// Ensure fs package is imported (needed by the Open method in renderer_test).
var _ fs.FS = (fs.FS)(nil)
