package cmd_test

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/vibewarden/vibewarden/internal/cli/cmd"
)

// TestInitCmd_DescribeFlag verifies that --describe writes PROJECT.md and
// mentions the description in the success message.
func TestInitCmd_DescribeFlag(t *testing.T) {
	dir := t.TempDir()

	origDir, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}
	if err := os.Chdir(dir); err != nil {
		t.Fatalf("chdir: %v", err)
	}
	t.Cleanup(func() { _ = os.Chdir(origDir) })

	root := cmd.NewRootCmd("test")
	var out bytes.Buffer
	root.SetOut(&out)
	root.SetArgs([]string{
		"init",
		"--describe", "a task management API",
		"describeapp",
	})

	if err := root.Execute(); err != nil {
		t.Fatalf("init --describe failed: %v", err)
	}

	// PROJECT.md must exist.
	projectMDPath := filepath.Join(dir, "describeapp", "PROJECT.md")
	data, err := os.ReadFile(projectMDPath) //nolint:gosec // test path
	if err != nil {
		t.Fatalf("PROJECT.md not created: %v", err)
	}
	if !strings.Contains(string(data), "a task management API") {
		t.Errorf("PROJECT.md does not contain description:\n%s", string(data))
	}
	if !strings.Contains(string(data), "describeapp") {
		t.Errorf("PROJECT.md does not contain project name:\n%s", string(data))
	}

	// Success message must mention the description.
	if !strings.Contains(out.String(), "a task management API") {
		t.Errorf("success message does not mention description:\n%s", out.String())
	}
	// Success message must mention PROJECT.md.
	if !strings.Contains(out.String(), "PROJECT.md") {
		t.Errorf("success message does not mention PROJECT.md:\n%s", out.String())
	}
}

// TestInitCmd_DescribeInjectsAgentsVibewardenMD verifies that --describe injects
// the description into AGENTS-VIBEWARDEN.md.
func TestInitCmd_DescribeInjectsAgentsVibewardenMD(t *testing.T) {
	dir := t.TempDir()

	origDir, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}
	if err := os.Chdir(dir); err != nil {
		t.Fatalf("chdir: %v", err)
	}
	t.Cleanup(func() { _ = os.Chdir(origDir) })

	root := cmd.NewRootCmd("test")
	root.SetOut(&bytes.Buffer{})
	root.SetArgs([]string{
		"init",
		"--describe", "a real-time chat service",
		"chatapp",
	})

	if err := root.Execute(); err != nil {
		t.Fatalf("init failed: %v", err)
	}

	agentsVWPath := filepath.Join(dir, "chatapp", "AGENTS-VIBEWARDEN.md")
	data, err := os.ReadFile(agentsVWPath) //nolint:gosec // test path
	if err != nil {
		t.Fatalf("AGENTS-VIBEWARDEN.md not found: %v", err)
	}
	if !strings.Contains(string(data), "a real-time chat service") {
		t.Errorf("AGENTS-VIBEWARDEN.md does not contain description:\n%s", string(data))
	}
}

// TestInitCmd_NoCLAUDEmdGenerated verifies that CLAUDE.md is NOT generated.
func TestInitCmd_NoCLAUDEmdGenerated(t *testing.T) {
	dir := t.TempDir()

	origDir, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}
	if err := os.Chdir(dir); err != nil {
		t.Fatalf("chdir: %v", err)
	}
	t.Cleanup(func() { _ = os.Chdir(origDir) })

	root := cmd.NewRootCmd("test")
	root.SetOut(&bytes.Buffer{})
	root.SetArgs([]string{"init", "noclaudeapp"})

	if err := root.Execute(); err != nil {
		t.Fatalf("init failed: %v", err)
	}

	claudeMDPath := filepath.Join(dir, "noclaudeapp", "CLAUDE.md")
	if _, err := os.Stat(claudeMDPath); err == nil {
		t.Error("CLAUDE.md must not be generated by vibew init")
	}

	claudeDir := filepath.Join(dir, "noclaudeapp", ".claude")
	if _, err := os.Stat(claudeDir); err == nil {
		t.Error(".claude/ directory must not be created by vibew init")
	}
}

// TestInitCmd_NoDescribeNoProjectMD verifies that when --describe is omitted,
// PROJECT.md is not written.
func TestInitCmd_NoDescribeNoProjectMD(t *testing.T) {
	dir := t.TempDir()

	origDir, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}
	if err := os.Chdir(dir); err != nil {
		t.Fatalf("chdir: %v", err)
	}
	t.Cleanup(func() { _ = os.Chdir(origDir) })

	root := cmd.NewRootCmd("test")
	root.SetOut(&bytes.Buffer{})
	root.SetArgs([]string{"init", "nodescapp"})

	if err := root.Execute(); err != nil {
		t.Fatalf("init failed: %v", err)
	}

	projectMDPath := filepath.Join(dir, "nodescapp", "PROJECT.md")
	if _, err := os.Stat(projectMDPath); err == nil {
		t.Error("PROJECT.md must not exist when --describe is not given")
	}
}

// TestInitCmd_NameFlag verifies that --name sets the project name.
func TestInitCmd_NameFlag(t *testing.T) {
	dir := t.TempDir()

	origDir, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}
	if err := os.Chdir(dir); err != nil {
		t.Fatalf("chdir: %v", err)
	}
	t.Cleanup(func() { _ = os.Chdir(origDir) })

	root := cmd.NewRootCmd("test")
	root.SetOut(&bytes.Buffer{})
	root.SetArgs([]string{"init", "--name", "namedproject"})

	if err := root.Execute(); err != nil {
		t.Fatalf("init --name failed: %v", err)
	}

	projectDir := filepath.Join(dir, "namedproject")
	if _, err := os.Stat(projectDir); err != nil {
		t.Errorf("expected project directory %q to exist: %v", projectDir, err)
	}
	if _, err := os.Stat(filepath.Join(projectDir, "vibewarden.yaml")); err != nil {
		t.Errorf("vibewarden.yaml not found in --name project: %v", err)
	}
}

// TestInitCmd_NameFlagOverriddenByPositionalArg verifies that a positional
// argument takes priority over --name when both are given.
func TestInitCmd_NameFlagOverriddenByPositionalArg(t *testing.T) {
	dir := t.TempDir()

	origDir, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}
	if err := os.Chdir(dir); err != nil {
		t.Fatalf("chdir: %v", err)
	}
	t.Cleanup(func() { _ = os.Chdir(origDir) })

	root := cmd.NewRootCmd("test")
	root.SetOut(&bytes.Buffer{})
	// Positional arg "positional" should win over --name "fromflag".
	root.SetArgs([]string{"init", "--name", "fromflag", "positional"})

	if err := root.Execute(); err != nil {
		t.Fatalf("init failed: %v", err)
	}

	// "positional" directory must exist.
	if _, err := os.Stat(filepath.Join(dir, "positional")); err != nil {
		t.Errorf("expected positional/ to exist: %v", err)
	}
	// "fromflag" directory must NOT exist.
	if _, err := os.Stat(filepath.Join(dir, "fromflag")); err == nil {
		t.Error("fromflag/ must not exist when positional arg is given")
	}
}

// TestInitCmd_Interactive simulates an interactive session by temporarily
// overriding cmd.IsTTY to return true and feeding stdin via a pipe.
func TestInitCmd_Interactive(t *testing.T) {
	dir := t.TempDir()

	origDir, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}
	if err := os.Chdir(dir); err != nil {
		t.Fatalf("chdir: %v", err)
	}
	t.Cleanup(func() { _ = os.Chdir(origDir) })

	// Create a pipe to simulate user input.
	r, w, err := os.Pipe()
	if err != nil {
		t.Fatalf("pipe: %v", err)
	}

	// Write: project name, description (each terminated by newline).
	input := "interactiveapp\na cool interactive project\n"
	if _, err := w.WriteString(input); err != nil {
		t.Fatalf("writing to pipe: %v", err)
	}
	if err := w.Close(); err != nil {
		t.Fatalf("closing write end: %v", err)
	}

	// Redirect stdin to the pipe for the duration of this test.
	origStdin := os.Stdin
	os.Stdin = r
	t.Cleanup(func() {
		os.Stdin = origStdin
		_ = r.Close()
	})

	// Override IsTTY to report interactive.
	origIsTTY := cmd.IsTTY
	cmd.IsTTY = func(*os.File) bool { return true }
	t.Cleanup(func() { cmd.IsTTY = origIsTTY })

	root := cmd.NewRootCmd("test")
	root.SetOut(&bytes.Buffer{})
	// No positional arg — should be filled by interactive prompts.
	root.SetArgs([]string{"init"})

	if err := root.Execute(); err != nil {
		t.Fatalf("interactive init failed: %v", err)
	}

	// Project directory must exist.
	projectDir := filepath.Join(dir, "interactiveapp")
	if _, err := os.Stat(projectDir); err != nil {
		t.Errorf("expected project dir %q: %v", projectDir, err)
	}

	// PROJECT.md must contain the description.
	data, err := os.ReadFile(filepath.Join(projectDir, "PROJECT.md")) //nolint:gosec // test path
	if err != nil {
		t.Fatalf("PROJECT.md not found: %v", err)
	}
	if !strings.Contains(string(data), "a cool interactive project") {
		t.Errorf("PROJECT.md missing description:\n%s", string(data))
	}
}

// TestInitCmd_InteractiveSkipsDescribeWhenEmpty verifies that when the user
// provides no description (empty line), PROJECT.md is not written.
func TestInitCmd_InteractiveSkipsDescribeWhenEmpty(t *testing.T) {
	dir := t.TempDir()

	origDir, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}
	if err := os.Chdir(dir); err != nil {
		t.Fatalf("chdir: %v", err)
	}
	t.Cleanup(func() { _ = os.Chdir(origDir) })

	r, w, err := os.Pipe()
	if err != nil {
		t.Fatalf("pipe: %v", err)
	}

	// Name given, empty description.
	if _, err := w.WriteString("nodescapp2\n\n"); err != nil {
		t.Fatalf("write: %v", err)
	}
	if err := w.Close(); err != nil {
		t.Fatalf("closing write end: %v", err)
	}

	origStdin := os.Stdin
	os.Stdin = r
	t.Cleanup(func() {
		os.Stdin = origStdin
		_ = r.Close()
	})

	origIsTTY := cmd.IsTTY
	cmd.IsTTY = func(*os.File) bool { return true }
	t.Cleanup(func() { cmd.IsTTY = origIsTTY })

	root := cmd.NewRootCmd("test")
	root.SetOut(&bytes.Buffer{})
	root.SetArgs([]string{"init"})

	if err := root.Execute(); err != nil {
		t.Fatalf("interactive init failed: %v", err)
	}

	if _, err := os.Stat(filepath.Join(dir, "nodescapp2", "PROJECT.md")); err == nil {
		t.Error("PROJECT.md must not be written when description is empty")
	}
}
