package cmd_test

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/vibewarden/vibewarden/internal/cli/cmd"
)

func TestNewWrapCmd_FlagCombinations(t *testing.T) {
	tests := []struct {
		name            string
		args            []string
		wantErr         bool
		wantOutContains string
		setup           func(dir string)
		checkFiles      []string
		absentFiles     []string
	}{
		{
			name:            "defaults generate vibewarden.yaml without docker-compose",
			args:            []string{},
			checkFiles:      []string{"vibewarden.yaml"},
			absentFiles:     []string{"docker-compose.yml"},
			wantOutContains: "VibeWarden added to project!",
		},
		{
			name:        "docker-compose.yml is never generated by wrap",
			args:        []string{},
			absentFiles: []string{"docker-compose.yml"},
		},
		{
			name:    "tls without domain returns error",
			args:    []string{"--tls"},
			wantErr: true,
		},
		{
			name:        "tls with domain succeeds without docker-compose",
			args:        []string{"--tls", "--domain", "example.com"},
			checkFiles:  []string{"vibewarden.yaml"},
			absentFiles: []string{"docker-compose.yml"},
		},
		{
			name:        "auth flag enabled produces vibewarden.yaml only",
			args:        []string{"--auth"},
			checkFiles:  []string{"vibewarden.yaml"},
			absentFiles: []string{"docker-compose.yml"},
		},
		{
			name:        "rate-limit flag enabled produces vibewarden.yaml only",
			args:        []string{"--rate-limit"},
			checkFiles:  []string{"vibewarden.yaml"},
			absentFiles: []string{"docker-compose.yml"},
		},
		{
			name:        "upstream port set",
			args:        []string{"--upstream", "8080"},
			checkFiles:  []string{"vibewarden.yaml"},
			absentFiles: []string{"docker-compose.yml"},
		},
		{
			name: "force flag overwrites existing vibewarden.yaml",
			args: []string{"--force"},
			setup: func(dir string) {
				if err := os.WriteFile(filepath.Join(dir, "vibewarden.yaml"), []byte("old"), 0o644); err != nil {
					t.Fatal(err)
				}
			},
			checkFiles: []string{"vibewarden.yaml"},
		},
		{
			name: "existing vibewarden.yaml without force returns error",
			args: []string{},
			setup: func(dir string) {
				if err := os.WriteFile(filepath.Join(dir, "vibewarden.yaml"), []byte("old"), 0o644); err != nil {
					t.Fatal(err)
				}
			},
			wantErr: true,
		},
		{
			name: "existing docker-compose.yml is left untouched (no error)",
			args: []string{},
			setup: func(dir string) {
				if err := os.WriteFile(filepath.Join(dir, "docker-compose.yml"), []byte("old"), 0o644); err != nil {
					t.Fatal(err)
				}
			},
			// docker-compose.yml exists before wrap and is not touched — no error expected.
			checkFiles: []string{"vibewarden.yaml", "docker-compose.yml"},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			dir := t.TempDir()

			if tt.setup != nil {
				tt.setup(dir)
			}

			// Build the cobra root and add the wrap command.
			root := cmd.NewRootCmd("test")
			var outBuf bytes.Buffer
			root.SetOut(&outBuf)

			// Run: vibewarden wrap <dir> <flags...>
			allArgs := append([]string{"wrap", dir}, tt.args...)
			root.SetArgs(allArgs)

			err := root.Execute()

			if (err != nil) != tt.wantErr {
				t.Fatalf("Execute() error = %v, wantErr %v", err, tt.wantErr)
			}

			if tt.wantOutContains != "" {
				if !strings.Contains(outBuf.String(), tt.wantOutContains) {
					t.Errorf("output %q does not contain %q", outBuf.String(), tt.wantOutContains)
				}
			}

			for _, filename := range tt.checkFiles {
				path := filepath.Join(dir, filename)
				if _, err := os.Stat(path); err != nil {
					t.Errorf("expected file %q to exist: %v", path, err)
				}
			}

			for _, filename := range tt.absentFiles {
				path := filepath.Join(dir, filename)
				if _, err := os.Stat(path); err == nil {
					t.Errorf("file %q should not exist but does", path)
				}
			}
		})
	}
}

func TestNewWrapCmd_AlwaysGeneratesAgentContextFiles(t *testing.T) {
	// vibew wrap always generates AGENTS-VIBEWARDEN.md and AGENTS.md.
	dir := t.TempDir()

	root := cmd.NewRootCmd("test")
	var outBuf bytes.Buffer
	root.SetOut(&outBuf)

	allArgs := []string{"wrap", dir}
	root.SetArgs(allArgs)

	if err := root.Execute(); err != nil {
		t.Fatalf("Execute() error = %v", err)
	}

	checkFiles := []string{
		"AGENTS-VIBEWARDEN.md",
		"AGENTS.md",
	}
	for _, relPath := range checkFiles {
		absPath := filepath.Join(dir, relPath)
		if _, err := os.Stat(absPath); err != nil {
			t.Errorf("expected file %q to exist: %v", absPath, err)
		}
	}
}

func TestNewWrapCmd_NoCLAUDEmdGenerated(t *testing.T) {
	// vibew wrap must NOT generate .claude/CLAUDE.md.
	dir := t.TempDir()

	root := cmd.NewRootCmd("test")
	root.SetOut(&bytes.Buffer{})
	root.SetArgs([]string{"wrap", dir})

	if err := root.Execute(); err != nil {
		t.Fatalf("Execute() unexpected error: %v", err)
	}

	claudePath := filepath.Join(dir, ".claude", "CLAUDE.md")
	if _, err := os.Stat(claudePath); err == nil {
		t.Errorf(".claude/CLAUDE.md must not be generated by vibew wrap")
	}
}

func TestNewWrapCmd_NoAgentFlag(t *testing.T) {
	// The --agent flag must not exist on the wrap command.
	root := cmd.NewRootCmd("test")
	root.SetArgs([]string{"wrap", "--help"})
	var out bytes.Buffer
	root.SetOut(&out)

	_ = root.Execute()
	helpOutput := out.String()
	if strings.Contains(helpOutput, "--agent") {
		t.Errorf("--agent flag must not exist on wrap command, but appears in help:\n%s", helpOutput)
	}
}

func TestNewWrapCmd_RenderedYAMLValid(t *testing.T) {
	// This test verifies that rendered vibewarden.yaml is non-empty and contains
	// expected keys.
	tests := []struct {
		name       string
		args       []string
		wantInYAML []string
	}{
		{
			name:       "default config contains server and upstream sections",
			args:       []string{},
			wantInYAML: []string{"server:", "upstream:", "port: 3000", "port: 8443"},
		},
		{
			name:       "default config enables TLS with self-signed provider",
			args:       []string{},
			wantInYAML: []string{"tls:", "enabled: true", "self-signed"},
		},
		{
			name:       "auth flag adds kratos and auth sections with new consolidated fields",
			args:       []string{"--auth"},
			wantInYAML: []string{"kratos:", "public_url:", "dsn:", "smtp:", "auth:", "identity_schema:"},
		},
		{
			name:       "rate-limit flag adds rate_limit section",
			args:       []string{"--rate-limit"},
			wantInYAML: []string{"rate_limit:", "per_ip:"},
		},
		{
			name:       "tls flag adds tls section with domain",
			args:       []string{"--tls", "--domain", "example.com"},
			wantInYAML: []string{"tls:", "enabled: true", "example.com"},
		},
		{
			name:       "upstream port appears in config",
			args:       []string{"--upstream", "4200"},
			wantInYAML: []string{"port: 4200"},
		},
		{
			name:       "overrides section is present as comment",
			args:       []string{},
			wantInYAML: []string{"overrides"},
		},
		{
			name:       "app.build defaults to current directory",
			args:       []string{},
			wantInYAML: []string{`build: "."`},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			dir := t.TempDir()

			root := cmd.NewRootCmd("test")
			allArgs := append([]string{"wrap", dir}, tt.args...)
			root.SetArgs(allArgs)

			if err := root.Execute(); err != nil {
				t.Fatalf("Execute() unexpected error: %v", err)
			}

			yamlBytes, err := os.ReadFile(filepath.Join(dir, "vibewarden.yaml"))
			if err != nil {
				t.Fatalf("reading vibewarden.yaml: %v", err)
			}
			yamlContent := string(yamlBytes)

			for _, want := range tt.wantInYAML {
				if !strings.Contains(yamlContent, want) {
					t.Errorf("vibewarden.yaml does not contain %q\n\nContent:\n%s", want, yamlContent)
				}
			}
		})
	}
}

// TestNewWrapCmd_AppBuildDefaultsToDot verifies that the generated
// vibewarden.yaml defaults to app.build = "." rather than app.image.
func TestNewWrapCmd_AppBuildDefaultsToDot(t *testing.T) {
	parent := t.TempDir()
	projectDir := filepath.Join(parent, "mywebapp")
	if err := os.MkdirAll(projectDir, 0o750); err != nil {
		t.Fatalf("mkdir: %v", err)
	}

	root := cmd.NewRootCmd("test")
	root.SetArgs([]string{"wrap", projectDir})

	if err := root.Execute(); err != nil {
		t.Fatalf("Execute() unexpected error: %v", err)
	}

	yamlBytes, err := os.ReadFile(filepath.Join(projectDir, "vibewarden.yaml"))
	if err != nil {
		t.Fatalf("reading vibewarden.yaml: %v", err)
	}
	content := string(yamlBytes)

	if !strings.Contains(content, `build: "."`) {
		t.Errorf("vibewarden.yaml does not contain active 'build: \".\"'\n\nContent:\n%s", content)
	}
	// "image:" must not appear as an active (uncommented) directive.
	for _, line := range strings.Split(content, "\n") {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "image:") {
			t.Errorf("vibewarden.yaml must not have an active 'image:' directive by default; found: %q\n\nContent:\n%s", line, content)
		}
	}
}

func TestNewWrapCmd_SuccessMessage(t *testing.T) {
	t.Run("success message mentions vibew dev", func(t *testing.T) {
		dir := t.TempDir()
		root := cmd.NewRootCmd("test")
		var outBuf strings.Builder
		root.SetOut(&outBuf)
		root.SetArgs([]string{"wrap", dir})

		if err := root.Execute(); err != nil {
			t.Fatalf("Execute() unexpected error: %v", err)
		}

		out := outBuf.String()
		if !strings.Contains(out, "vibew dev") {
			t.Errorf("success message does not mention 'vibew dev'\n\nOutput:\n%s", out)
		}
		if !strings.Contains(out, "VibeWarden added to project!") {
			t.Errorf("success message does not contain 'VibeWarden added to project!'\n\nOutput:\n%s", out)
		}
	})

	t.Run("success message does not mention docker compose up", func(t *testing.T) {
		dir := t.TempDir()
		root := cmd.NewRootCmd("test")
		var outBuf strings.Builder
		root.SetOut(&outBuf)
		root.SetArgs([]string{"wrap", dir})

		if err := root.Execute(); err != nil {
			t.Fatalf("Execute() unexpected error: %v", err)
		}

		out := outBuf.String()
		if strings.Contains(out, "docker compose up") {
			t.Errorf("success message must not mention 'docker compose up'\n\nOutput:\n%s", out)
		}
	})
}
